apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: games-keep-the-sequence-website
  annotations:
    custom.backstage.io/component-id: "522fc44d5abf9f59acafbb6561f0c5fae0420d0f6cd41cfa0712a166f38443b5"
    github.com/project-slug: rtsarakaki/keep-the-sequence
spec:
  type: website
  lifecycle: production
  owner: developers
  system: games
