AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for GitHub Actions OIDC - The Game'

Parameters:
  GitHubRepository:
    Type: String
    Description: 'GitHub repository in format owner/repo-name (e.g., usuario/keep-the-sequence)'
    AllowedPattern: '^[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+$'
    ConstraintDescription: 'Must be in format owner/repo-name'
  
  AllowedBranch:
    Type: String
    Description: 'Optional - Specific branch to allow. Leave empty to allow all branches. Example: main'
    Default: ''

Conditions:
  HasAllowedBranch: !Not [!Equals [!Ref AllowedBranch, '']]

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-deploy-role
      Description: 'Role for GitHub Actions to deploy The Game infrastructure'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub:
                  !If
                    - HasAllowedBranch
                    - !Join
                        - ''
                        - - 'repo:'
                          - !Ref GitHubRepository
                          - ':ref:refs/heads/'
                          - !Ref AllowedBranch
                    - !Join
                        - ''
                        - - 'repo:'
                          - !Ref GitHubRepository
                          - ':*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/CloudFormationFullAccess
      MaxSessionDuration: 3600

Outputs:
  RoleArn:
    Description: 'ARN of the IAM Role for GitHub Actions'
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: GitHubActionsRoleArn
  
  GitHubRepository:
    Description: 'GitHub repository that can assume this role'
    Value: !Ref GitHubRepository
